export const Themes = [
  // APPEND HERE
  {
    tailwindColor: "pink",
    bodyTextClass: "text-white",
    btnTextClass: "text-white",
    dropdownTextClass: "text-white",
    overrideToggle: false,
    overrideAnchor: false,
  },
  {
    tailwindColor: "red",
    bodyTextClass: "text-white",
    btnTextClass: "text-white",
    dropdownTextClass: "text-white",
    overrideToggle: false,
    overrideAnchor: false,
  },
  {
    tailwindColor: "blue",
    bodyTextClass: "text-white",
    btnTextClass: "text-white",
    dropdownTextClass: "text-white",
    overrideToggle: false,
    overrideAnchor: true,
    anchorColor: "emerald",
  },
  {
    tailwindColor: "teal",
    bodyTextClass: "text-white",
    btnTextClass: "text-black",
    dropdownTextClass: "text-white",
    overrideToggle: true,
    toggleColor: "amber",
    overrideAnchor: false,
  },
  {
    tailwindColor: "cyan",
    bodyTextClass: "text-white",
    btnTextClass: "text-black",
    dropdownTextClass: "text-white",
    overrideToggle: false,
    overrideAnchor: false,
  },
];
