name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/SamuelQuinones/password-generator/projects/2'
        column_name: 'inbox'

#     - name: Assign issues and pull requests with `assigned` label to project 2
#       uses: srggrs/assign-one-project-github-action@1.2.1
#       if: |
#         contains(github.event.issue.labels.*.name, 'accepted') ||
#         contains(github.event.pull_request.labels.*.name, 'accepted')
#       with:
#         project: 'https://github.com/SamuelQuinones/password-generator/projects/2'
#         column_name: 'To do'
